/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as DonationsRouteImport } from './routes/donations'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as DonationsIndexRouteImport } from './routes/donations.index'
import { Route as DonationsVideosRouteImport } from './routes/donations.videos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const DonationsRoute = DonationsRouteImport.update({
  id: '/donations',
  path: '/donations',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DonationsIndexRoute = DonationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DonationsRoute,
} as any)
const DonationsVideosRoute = DonationsVideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => DonationsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/donations': typeof DonationsRouteWithChildren
  '/integrations': typeof IntegrationsRoute
  '/settings': typeof SettingsRoute
  '/donations/videos': typeof DonationsVideosRoute
  '/donations/': typeof DonationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/integrations': typeof IntegrationsRoute
  '/settings': typeof SettingsRoute
  '/donations/videos': typeof DonationsVideosRoute
  '/donations': typeof DonationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/donations': typeof DonationsRouteWithChildren
  '/integrations': typeof IntegrationsRoute
  '/settings': typeof SettingsRoute
  '/donations/videos': typeof DonationsVideosRoute
  '/donations/': typeof DonationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/donations'
    | '/integrations'
    | '/settings'
    | '/donations/videos'
    | '/donations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/integrations'
    | '/settings'
    | '/donations/videos'
    | '/donations'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/donations'
    | '/integrations'
    | '/settings'
    | '/donations/videos'
    | '/donations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  DonationsRoute: typeof DonationsRouteWithChildren
  IntegrationsRoute: typeof IntegrationsRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donations': {
      id: '/donations'
      path: '/donations'
      fullPath: '/donations'
      preLoaderRoute: typeof DonationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donations/': {
      id: '/donations/'
      path: '/'
      fullPath: '/donations/'
      preLoaderRoute: typeof DonationsIndexRouteImport
      parentRoute: typeof DonationsRoute
    }
    '/donations/videos': {
      id: '/donations/videos'
      path: '/videos'
      fullPath: '/donations/videos'
      preLoaderRoute: typeof DonationsVideosRouteImport
      parentRoute: typeof DonationsRoute
    }
  }
}

interface DonationsRouteChildren {
  DonationsVideosRoute: typeof DonationsVideosRoute
  DonationsIndexRoute: typeof DonationsIndexRoute
}

const DonationsRouteChildren: DonationsRouteChildren = {
  DonationsVideosRoute: DonationsVideosRoute,
  DonationsIndexRoute: DonationsIndexRoute,
}

const DonationsRouteWithChildren = DonationsRoute._addFileChildren(
  DonationsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  DonationsRoute: DonationsRouteWithChildren,
  IntegrationsRoute: IntegrationsRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
